title: Doorbellieslens
  description: Fotografie website
  baseurl: ""
  url: "https://fotografie-elbrich.netlify.app"
  collections:
    pages:
      output: true
      permalink: /:name
  defaults:
    - scope:
        path: ""
        type: pages
      values:
        layout: page