[build]
  base = "./"
  publish = "./"
  command = ""

[build.environment]
  ASSETS_DIR = "assets/img"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false