[build]
  base = "./" 
  publish = "./" 
  command = "echo 'No build step required'"

[build.environment]
  ASSETS_DIR = "assets/img"

[[headers]]
  for = "/assets/img/*"  
  [headers.values]
    Cache-Control = "public, max-age=31536000" 

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = false  

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false 

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    