backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "home"
    label: "Home"
    folder: "content/home"
    create: false
    slug: "index"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Ondertitel", name: "subtitle", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "text" }
      - { label: "Knoptekst", name: "button_text", widget: "string" }
      - { label: "Over mij - Titel", name: "about_title", widget: "string" }
      - { label: "Over mij - Beschrijving", name: "about_description", widget: "text" }
      - { label: "Over mij - Knoptekst", name: "about_button_text", widget: "string" }
      - label: "Recente Projecten"
        name: "recent_projects"
        widget: "list"
        fields:
          - { label: "Afbeelding", name: "image", widget: "image" }
          - { label: "Categorie", name: "category", widget: "string" }
          - { label: "Titel", name: "title", widget: "string" }
      - label: "Diensten"
        name: "services"
        widget: "list"
        fields:
          - { label: "Afbeelding", name: "image", widget: "image" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Beschrijving", name: "description", widget: "text" }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Auteur", name: "author", widget: "string" }
          - { label: "Functie", name: "role", widget: "string" }