backend:
  name: git-gateway
  branch: main # Verander dit naar jouw Git-branch (bijv. main of master)

media_folder: "images" # Map waar geüploade media (zoals foto's) worden opgeslagen
public_folder: "/images" # Publieke URL voor media

collections:
  - name: "index"
    label: "Home"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Intro Text", name: "intro_text", widget: "text" }
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Role", name: "role", widget: "string" }

  - name: "contact"
    label: "Contact"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Contact Info"
        name: "contact_info"
        widget: "object"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answer", widget: "text" }

  - name: "prijzen"
    label: "Prijzen"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Packages"
        name: "packages"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Price", name: "price", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Features"
            name: "features"
            widget: "list"
          - { label: "Button Text", name: "button", widget: "string" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }

  - name: "agenda"
    label: "Agenda"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - label: "Availability"
        name: "availability"
        widget: "text"

  - name: "wie-ben-ik"
    label: "Wie ben ik"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Intro", name: "intro", widget: "text" }