backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - name: "index"
        label: "Home"
        file: "content/index.json"
        fields:
          - { name: "hero_title", label: "Hero Titel", widget: "string" }
          - { name: "hero_subtitle", label: "Hero Subtitel", widget: "string" }
          - { name: "hero_text", label: "Hero Tekst", widget: "markdown" }
          - { name: "about_title", label: "Over Titel", widget: "string" }
          - { name: "about_text", label: "Over Tekst", widget: "markdown" }
          - { name: "services_title", label: "Diensten Titel", widget: "string" }
          - name: "services"
            label: "Diensten"
            widget: "list"
            fields:
              - { name: "title", label: "Titel", widget: "string" }
              - { name: "description", label: "Beschrijving", widget: "markdown" }
              - { name: "image", label: "Afbeelding", widget: "image" }
          - { name: "testimonials_title", label: "Testimonials Titel", widget: "string" }
          - name: "testimonials"
            label: "Testimonials"
            widget: "list"
            fields:
              - { name: "quote", label: "Citaat", widget: "markdown" }
              - { name: "author", label: "Auteur", widget: "string" }
              - { name: "role", label: "Rol", widget: "string" }
      - name: "wie_ben_ik"
        label: "Wie ben ik"
        file: "content/wie-ben-ik.json"
        fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "subtitle", label: "Subtitel", widget: "string" }
          - { name: "greeting", label: "Begroeting", widget: "string" }
          - { name: "text", label: "Tekst", widget: "markdown" }
          - { name: "image", label: "Afbeelding", widget: "image" }
      - name: "prijzen"
        label: "Prijzen"
        file: "content/prijzen.json"
        fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "subtitle", label: "Subtitel", widget: "string" }
          - name: "packages"
            label: "Pakketten"
            widget: "list"
            fields:
              - { name: "title", label: "Titel", widget: "string" }
              - { name: "price", label: "Prijs", widget: "string" }
              - { name: "description", label: "Beschrijving", widget: "markdown" }
              - name: "features"
                label: "Kenmerken"
                widget: "list"
                field: { name: "feature", label: "Kenmerk", widget: "string" }
      - name: "agenda"
        label: "Agenda"
        file: "content/agenda.json"
        fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "subtitle", label: "Subtitel", widget: "string" }
          - { name: "availability_title", label: "Beschikbaarheid Titel", widget: "string" }
          - { name: "availability_text", label: "Beschikbaarheid Tekst", widget: "markdown" }
          - { name: "calendar_title", label: "Kalender Titel", widget: "string" }
          - { name: "calendar_note", label: "Kalender Notitie", widget: "string" }
      - name: "contact"
        label: "Contact"
        file: "content/contact.json"
        fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "subtitle", label: "Subtitel", widget: "string" }
          - { name: "form_title", label: "Formulier Titel", widget: "string" }
          - { name: "form_text", label: "Formulier Tekst", widget: "markdown" }
          - { name: "contact_email", label: "E-mail", widget: "string" }
          - { name: "contact_phone", label: "Telefoon", widget: "string" }
          - { name: "contact_address", label: "Adres", widget: "string" }
          - { name: "faq_title", label: "FAQ Titel", widget: "string" }
          - name: "faqs"
            label: "Veelgestelde Vragen"
            widget: "list"
            fields:
              - { name: "question", label: "Vraag", widget: "string" }
              - { name: "answer", label: "Antwoord", widget: "markdown" }
      - name: "portfolio"
        label: "Portfolio"
        file: "content/portfolio.json"
        fields:
          - { name: "title", label: "Titel", widget: "string" }
          - { name: "subtitle", label: "Subtitel", widget: "string" }
          - { name: "intro_title", label: "Intro Titel", widget: "string" }
          - { name: "intro_text", label: "Intro Tekst", widget: "markdown" }
          - name: "items"
            label: "Portfolio Items"
            widget: "list"
            fields:
              - { name: "image", label: "Afbeelding", widget: "image" }