backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads" # Where media files will be stored
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "public/index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "public/who-am-i.html"
        label: "Who Am I?"
        name: "who-am-i"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "public/portfolio.html"
        label: "Portfolio"
        name: "portfolio"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Items", name: "items", widget: "list", fields:
              - { label: "Category", name: "category", widget: "select", options: ["Gezin Shoot", "Liefdes Shoot", "Geboorte", "Newborn"] }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
            }
  - name: "reviews"
    label: "Client Reviews"
    folder: "public/assets/reviews"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Review", name: "review", widget: "text" }
  - name: "agenda"
    label: "Agenda"
    file: "public/agenda.html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Dates", name: "dates", widget: "list", fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Available", name: "available", widget: "boolean" }
        }
  - name: "pricing"
    label: "Pricing"
    file: "public/pricing.html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Packages", name: "packages", widget: "list", fields:
          - { label: "Package Name", name: "name", widget: "string" }
          - { label: "Price", name: "price", widget: "number" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }
        }
  - name: "contact"
    label: "Contact"
    file: "public/contact.html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }