backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero-title", widget: "string" }
          - { label: "Hero Text", name: "hero-text", widget: "text" }
      - file: "wie-ben-ik.html"
        label: "Wie ben ik?"
        name: "wie-ben-ik"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "portfolio.html"
        label: "Portfolio"
        name: "portfolio"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Items", name: "items", widget: "list", fields:
              - { label: "Category", name: "category", widget: "select", options: ["gezin", "liefdes", "geboorte", "newborn"] }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
            }
      - file: "reviews.html"
        label: "Reviews"
        name: "reviews"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Testimonials", name: "testimonials", widget: "list", fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
            }
      - file: "prijzen.html"
        label: "Prijzen"
        name: "prijzen"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Packages", name: "packages", widget: "list", fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "number" }
              - { label: "Description", name: "description", widget: "text" }
            }
      - file: "agenda.html"
        label: "Agenda"
        name: "agenda"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Dates", name: "dates", widget: "list", fields:
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Available", name: "available", widget: "boolean" }
            }
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }