backend:
  name: git-gateway
  branch: main  # Wijzig naar 'master' als je branch anders is
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "public/index.html"
        label: "Home"
        name: "index"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - { label: "Hoofdinhoud", name: "body", widget: "markdown" }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Item Titel", name: "item_title", widget: "string" }
                  - { label: "Item Beschrijving", name: "item_description", widget: "markdown" }
      - file: "public/portfolio.html"
        label: "Portfolio"
        name: "portfolio"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - { label: "Hoofdinhoud", name: "body", widget: "markdown" }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Item Titel", name: "item_title", widget: "string" }
      - file: "public/wie-ben-ik.html"
        label: "Wie ben ik"
        name: "wie-ben-ik"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
      - file: "public/prijzen.html"
        label: "Prijzen"
        name: "prijzen"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Item Titel", name: "item_title", widget: "string" }
                  - { label: "Item Beschrijving", name: "item_description", widget: "markdown" }
                  - { label: "Prijs", name: "price", widget: "string" }
                  - label: "Details"
                    name: "details"
                    widget: "list"
                    fields:
                      - { label: "Detail", name: "detail", widget: "string" }
      - file: "public/agenda.html"
        label: "Agenda"
        name: "agenda"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
          - label: "Beschikbaarheid"
            name: "availability"
            widget: "list"
            fields:
              - { label: "Week", name: "week", widget: "string" }
              - label: "Dagen"
                name: "days"
                widget: "list"
                fields:
                  - { label: "Dag", name: "day", widget: "string" }
                  - { label: "Status", name: "status", widget: "string" }
      - file: "public/contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "string", required: false }
          - label: "Secties"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Sectie Titel", name: "section_title", widget: "string" }
              - { label: "Sectie Inhoud", name: "section_content", widget: "markdown" }
          - label: "FAQ's"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "Vraag", name: "question", widget: "string" }
              - { label: "Antwoord", name: "answer", widget: "markdown" }
          - label: "Contactgegevens"
            name: "contact_info"
            widget: "object"
            fields:
              - { label: "E-mail", name: "email", widget: "string" }
              - { label: "Telefoon", name: "phone", widget: "string" }
              - { label: "Adres", name: "address", widget: "string" }