backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "index"
    label: "Index Page"
    files:
      - file: "public/content/index.json"
        label: "Index Content"
        name: "index_content"
        fields:
          - { label: "Hero Title", name: "hero.title", widget: "string" }
          - { label: "Hero Location", name: "hero.location", widget: "string" }
          - { label: "Hero Description", name: "hero.description", widget: "text" }
          - { label: "Hero Button", name: "hero.button", widget: "string" }
          - { label: "About Title", name: "about.title", widget: "string" }
          - { label: "About Description", name: "about.description", widget: "text" }
          - { label: "About Button", name: "about.button", widget: "string" }
          - { label: "Recent Projects Title", name: "recent_projects.title", widget: "string" }
          - { label: "Recent Projects View All", name: "recent_projects.view_all", widget: "string" }
          - label: "Recent Projects"
            name: "recent_projects.projects"
            widget: "list"
            fields:
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
          - { label: "Services Title", name: "services.title", widget: "string" }
          - label: "Services"
            name: "services.items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "Testimonials Title", name: "testimonials.title", widget: "string" }
          - { label: "Testimonials Subtitle", name: "testimonials.subtitle", widget: "string" }
          - label: "Testimonials"
            name: "testimonials.items"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Position", name: "position", widget: "string" }
          - { label: "Contact Title", name: "contact.title", widget: "string" }
          - { label: "Contact Description", name: "contact.description", widget: "text" }
          - { label: "Contact Button", name: "contact.button", widget: "string" }
          - { label: "Contact Info Title", name: "contact_info.title", widget: "string" }
          - { label: "Contact Info Email", name: "contact_info.email", widget: "string" }
          - { label: "Contact Info Email Link Text", name: "contact_info.email_link_text", widget: "string" }
          - { label: "Contact Info Legal Title", name: "contact_info.legal_title", widget: "string" }
          - { label: "Contact Info KVK", name: "contact_info.kvk", widget: "string" }
          - { label: "Contact Info Privacy Policy", name: "contact_info.privacy_policy", widget: "string" }
          - { label: "Contact Info Social Title", name: "contact_info.social_title", widget: "string" }